/// Description
Class IRISDemo.BO.Customer.Operation.CreateOrUpdateCustomerReq Extends (%Persistent, Ens.Request)
{

Property CustomerInfo As IRISDemo.BO.Customer.Operation.CustomerInfo;

Storage Default
{
<Data name="CreateOrUpdateCustomerReqDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>CustomerInfo</Value>
</Value>
</Data>
<DataLocation>^IRISDemo.B52AF.CreateOrUpdAE95D</DataLocation>
<DefaultData>CreateOrUpdateCustomerReqDefaultData</DefaultData>
<IdLocation>^IRISDemo.B52AF.CreateOrUpdAE95D</IdLocation>
<IndexLocation>^IRISDemo.B52AF.CreateOrUpdAE95I</IndexLocation>
<StreamLocation>^IRISDemo.B52AF.CreateOrUpdAE95S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
